version: 7.8.{build}

artifacts:
  - path: Framework.zip # pushing a single file
  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: Rc.Core\bin\$(configuration)
    name: Rc.Core

  # pushing entire folder as a zip archive
  - path: logs

branches:
  only:
    - master
platform:
  - Any CPU
configuration:
  - Debug
  
environment:
  VS_VERSION: vs2015
build:
  parallel: true                  # enable MSBuild parallel builds
  project: Rc.Core.sln      # path to Visual Studio solution or project
