version: 7.7.{build}


branches:
  only:
    - master
platform:
  - Any CPU
configuration:
  - Debug
  
environment:
  VS_VERSION: vs2014
build:
  parallel: true                  # enable MSBuild parallel builds
  project: Rc.Core.sln      # path to Visual Studio solution or project
