version: 7.7.{build}


branches:
  only:
    - master
platform:
  - x64
configuration:
  - Debug
  
environment:
  VS_VERSION: vs2014
  BUILD_PLATFORM: 'x64'
build:
  parallel: true                  # enable MSBuild parallel builds
  project: MyTestAzureCS.sln      # path to Visual Studio solution or project
